version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '00:00'
    assignees:
      - 'Dobefu'
    reviewers:
      - 'Dobefu'
